### ISSUE TITLE
now cant run it

### ISSUE THREAD

**Issue by johnfelipe** [OpeningDesign/draw#7]
this is my steps:

	curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

	sudo apt-get install -y nodejs

	sudo apt-get update && sudo apt-get install libcairo2-dev libjpeg62-dev libpango1.0-dev libgif-dev build-essential g++ git

	sudo su
	ufw allow 9002/tcp

	exit

	git clone https://github.com/OpeningDesign/draw.git

	cd draw

	bin/run.sh

and this is error show:

	Ensure that all dependencies are up to date...
	start...
	DirtyDB is used. This is fine for testing but not recommended for production.
	/home/felipe/draw/node_modules/bindings/bindings.js:96
	  throw err
	  ^

	Error: Could not locate the bindings file. Tried:
	 → /home/felipe/draw/node_modules/contextify/build/contextify.node
	 → /home/felipe/draw/node_modules/contextify/build/Debug/contextify.node
	 → /home/felipe/draw/node_modules/contextify/build/Release/contextify.node
	 → /home/felipe/draw/node_modules/contextify/out/Debug/contextify.node
	 → /home/felipe/draw/node_modules/contextify/Debug/contextify.node
	 → /home/felipe/draw/node_modules/contextify/out/Release/contextify.node
	 → /home/felipe/draw/node_modules/contextify/Release/contextify.node
	 → /home/felipe/draw/node_modules/contextify/build/default/contextify.node
	 → /home/felipe/draw/node_modules/contextify/compiled/6.11.4/linux/x64/contextify.node
		at bindings (/home/felipe/draw/node_modules/bindings/bindings.js:93:9)
		at Object.<anonymous> (/home/felipe/draw/node_modules/contextify/lib/contextify.js:1:96)
		at Module._compile (module.js:570:32)
		at Object.Module._extensions..js (module.js:579:10)
		at Module.load (module.js:487:32)
		at tryModuleLoad (module.js:446:12)
		at Function.Module._load (module.js:438:3)
		at Module.require (module.js:497:17)
		at require (internal/module.js:20:19)
		at Object.<anonymous> (/home/felipe/draw/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)

how fix it?

**Comment by johnfelipe** [comment]
`npm install contextify`

fixed
